version: "2"

services:
  db:
    image: hope/mongodb:3.2
    container_name: db.storage
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/db:/data/db
    networks:
      - private

  auth:
    build: ./containers/auth
    container_name: auth.storage
    ports:
      - "3001:3000"
    networks:
      - private

networks:
  private:
    driver: bridge
